name: addressmatching_unitest
on: 
  pull_request:
    branches:
      - main
jobs:
  unittesting:
    runs-on: ubuntu-latest
    environment: devops
    steps:
      - name: Checkut code
        uses: actions/checkout@v4
      - name: Run unittest job
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: test/testpipeline/test_transform.ipynb
          existing-cluster-id: 0305-173512-wwwltma1
          git-commit: "${{ github.event.pull_request.head.sha || github.sha }}"
